### PR TITLE
Trac 891

### PR DESCRIPTION
**Pull request by cdeaneGit**
The file utk-fedora-gsearch-solr-config/fedoragsearch-transforms/islandora_transforms/slurp_all_MODS_to_solr.xslt was revised to add the field utk_mods_etd_name_committee_member_ms.
The way to test is for userA to submit a thesis to the TRACE Repository and when filling out the form, have more than one committee member.  Then see if the MODS.xml that is created show correct results for committee members.

Please review.
@CanOfBees @markpbaggett

### CODE REVIEW

**Comment by markpbaggett** [comment]
@cdeaneGit reviewing now.

**Comment by markpbaggett** [comment]
@cdeaneGit, b41b94a3babba6604f2f6e3ec404cee3aa669be9 looks fine, but you have 23 other commits before that that you are trying to merge into the code base that touch other things.  I think Bridger and I need to retest this in order to confirm the other templates this touches still work as expected.

Obviously we're all ready to move on at this point, so I just want to get this merged, but in the future we have to make sure our p.r.s only touch the parts of the codebase that it is intended to affect. 

If you look through your code, your first commit is fine -- no conflicts, only touching the code that is intended.  It looks like that continued to be the case until 6 days ago and this commit: 982bf9dbff0a400b9b806a58e815cd1803131ae5

Here you start touching and playing with the author template. Your p.r. says this is about the committee member template. Why would we change anything about another template here? Before all is done, you can see that your branch here makes changes to 4 different templates:

* author
* committee member
* date of award
* thesis advisor

This makes testing this difficult and puts a lot of responsibility on the reviewer and the merger / assignee. 

@CanOfBees, any thoughts here?

**Comment by CanOfBees** [comment]
@cdeaneGit @markpbaggett, I'd like to close this too, but it's become increasingly difficult to parse the changes that have been made. I had thought that closing/reopening the PR would have helped avoid some of the extra commits.

I'll try to test it now.

**Comment by cdeaneGit** [comment]
I will cease and desist.  I just want to get the template revised correctly.

**Comment by cdeaneGit** [comment]
Closing #12

**Pull request closed without merging**
