### PR TITLE
Address DIT-1280.

### PR DESCRIPTION
**Pull request by markpbaggett**
**Jira Issue**: [DIT-1280](https://jirautk.atlassian.net/browse/DIT-1280)

## What does this Pull Request do?

Adds new fields based on the rows in green in this spreadsheet.

## How should this be tested?

1. Add an object to islandora vagrant
2. Replace its metadata record with the one in test records
3. Look at its Solr document:  [http://localhost:8080/solr/collection1/select?q=PID%3A%22test:1%22&fl=*&wt=json&indent=true](http://localhost:8080/solr/collection1/select?q=PID%3A%22test:1%22&fl=*&wt=json&indent=true)
4. Overwrite the associated transform: /var/lib/tomcat7/webapps/fedoragsearch/WEB-INF/classes/fgsconfigFinal/index/FgsIndex/islandora_transforms/slurp_all_MODS_to_solr.xslt
5. Restart tomcat or fedoraGSearch: http://localhost:8080/manager/
6. Update gsearch for your object with curl or python or GUI
7. Check that new fields that should exist do exist

```python

import requests

my_pid = 'test:1'
requests.post(f'http://localhost:8080/fedorafedoragsearch/rest?operation=updateIndex&action=fromPid&value={my_pid}', auth=('fedoraAdmin', 'fedoraAdmin'))

```

## Interested parties

@CanOfBees @mlhale7

### CODE REVIEW

**Comment by markpbaggett** [comment]
@mlhale7 and @CanOfBees, I wasn't sure if not having a test record was making this hard to test, so I added one to test records with sample fields for things my pr should add and things it should ignore.

**Review by mlhale7 — APPROVED** [review]
This transform added the appropriate utk_mods Solr fields to an object newly added to Islandora vagrant. It addresses all of the rows in green on the sheet.

In looking at the transform, I had a comment for us to consider going forward. Since we aren't really slurping in all mods anymore, I wondered if renaming this transform would be helpful in more accurately describing what it does. Maybe utk_MODS_to_solr.xslt?

**Comment by mlhale7** [comment]
@markpbaggett - just missed this! Let me know if I need to revert.

**Comment by markpbaggett** [comment]
@mlhale7, I don't think so if everything works.  If you mean the include, I don't even think we use it so I'm not sure why it's there, but I added it back since it didn't have anything to do with my PR.

**Comment by mlhale7** [comment]
It worked, so we should be good.

**Pull request merged**
