### PR TITLE
Address VVMC-108.

### PR DESCRIPTION
**Pull request by markpbaggett**
Just noticed this ticket has been open since last spring:

[VVMC-108](https://jira.lib.utk.edu/browse/VVMC-108)

This should fix it.

### CODE REVIEW

**Comment by markpbaggett** [comment]
@CanOfBees, listing you here since this has been open for a month and no one has noticed.

**Comment by CanOfBees** [comment]
@markpbaggett thanks for the reminder -- I'll get this squared away.

**Review by CanOfBees — CHANGES_REQUESTED** [review]
@markpbaggett would you please change this to match on the full path; e.g. `match="mod:mods/mods:note[@displayLabel='instrumentation']"`?

**Comment by markpbaggett** [comment]
@CanOfBees , absolutely.  Sorry about that.

**Review by CanOfBees — APPROVED** [review]
@markpbaggett awesome - thanks!

**Pull request merged**
