### PR TITLE
Address DIT-1342 (and 1346)

### PR DESCRIPTION
**Pull request by CanOfBees**
**Jira Issue**: [DIT-1342](https://jirautk.atlassian.net/browse/DIT-1342) (and [DIT-1346](https://jirautk.atlassian.net/browse/DIT-1346))

## What does this Pull Request do?
This PR suppresses the collections:uarc and collections:gsmrc objects from browse/search results.

## What's new?
Two new PIDs in the solrconfig.xml's fq append list.

## How should this be tested?
Read the change. Do the PIDs match the appriopriate PIDs?

## Interested parties
@mlhale7

### CODE REVIEW

**Comment by mlhale7** [comment]
Thanks for working on this Bridger. While the PIDs match (though we'll also want to include collections%3Ampa), I am still seeing these records show up in the interface. Let me know if clearing the Drupal cache or other actions help.

**Comment by CanOfBees** [comment]
@mlhale7 re-check when you have a moment. It looks like clearing the cache addressed those showing up.

**Comment by mlhale7** [comment]
Yes, when I check now these collections are no longer showing up. If you can add collections:mpa, I'm happy to close and merge.

**Review by mlhale7 — APPROVED** [review]
@CanOfBees - thanks for this! It looks good. Just an fyi that it's possible you might need to clear the Drupal cache again for MPA to disappear.

**Pull request merged**
